### ISSUE TITLE
Graph preview doesn't work

### ISSUE THREAD

**Issue by russellrobinson** [bzixilu/dotplugin#11]
All I get is "No preveiw is available" after a minute of "Analyzing".

See attached file.

Thoughts?

[bug.zip](https://github.com/bzixilu/dotplugin/files/4726800/bug.zip)

**Comment by breandan** [comment]
Encountered the following error after installation on `IU-202.5792.28`:

```
The IDE failed to install some plugins.

Most probably, this happened because of a change in a serialization format.
Please try again, and if the problem persists, please report it
to http://jb.gg/ide/critical-startup-errors

The cause: Source file missing: /home/breandan/.cache/JetBrains/IntelliJIdea2020.2/plugins/dotplugin.zip`
```

**Comment by banshee** [comment]
Version 1.2 of the plugin works for me with this ide version:

IntelliJ IDEA 2020.1.4 (Ultimate Edition)
Build #IU-201.8743.12, built on July 21, 2020
Runtime version: 11.0.7+10-b765.65 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-40-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 5964M
Cores: 12
Non-Bundled Plugins: name.kropp.intellij.makefile, org.jetbrains.kotlin, org.intellij.scala, com.jetbrains.php, org.plugin.dot.id
Current Desktop: ubuntu:GNOME

**Comment by ptrsrn** [comment]
For me it was `&nbsp;`  in labels that prevented the plugin from rendering the preview.

**Comment by bzixilu** [comment]
Thank you for reporting. I've added information about problems that happened during the preview rendering.
I hope it will help to understand what it's going on.
Please check v1.3 of the plugin: https://plugins.jetbrains.com/plugin/10312-dot-language/versions/stable/156938

**Comment by bzixilu** [comment]
@russellrobinson I've checked your example. The problem is that for some reason graphviz doesn't support #-like comment.
