### ISSUE TITLE
No such node specified in graph when nodes are specified

### ISSUE THREAD

**Issue by banshee** [bzixilu/dotplugin#12]
dotplugin seems to want nodes specified on their own, since this has errors:

```
digraph {
 a -> b
}
```

a and b are both flagged with "no such node specified in graph," but they're definitely specified.

This version doesn't have errors, but it's weird - you wouldn't normally do this:

```
digraph {
    a -> b
    a
    b
}
```

**Comment by bzixilu** [comment]
I agree, it seems that this feature is not very useful. I've turned it off.

**Comment by bzixilu** [comment]
@banshee the version with this fix is now available in plugins repo: https://plugins.jetbrains.com/plugin/10312-dot-language/versions/stable/158041
