### ISSUE TITLE
Shebang support

### ISSUE THREAD

**Issue by guy4261** [bzixilu/dotplugin#17]
Hello! Thanks for this awesome plugin! The world needs more graphviz!

I like adding `#!/usr/bin/env dot -O -Tpng` to the top of my `.dot` files, and to `chmod u+x foo.dot` . This way `./foo.dot` generates `foo.dot.png`. While not in the `dot` spec, it's makes sense (in terms of Linux) to add a shebang for a text file's first line.

So my question is - can you make the plugin ignore the first line in the `.dot` file if it starts with a `#!` ?

Thanks a lot! Even if you don't add it, this plugin's still awesome!!! 🙇

**Comment by bzixilu** [comment]
@guy4261 the version with Shebang support is now available in plugins repo: https://plugins.jetbrains.com/plugin/10312-dot-language/versions/stable/158041
