### ISSUE TITLE
getting "Error during rasterization" on version 1.4.1

### ISSUE THREAD

**Issue by ozyavin** [bzixilu/dotplugin#31]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/7387682/199249754-4724a261-9d41-4fc6-915d-6f65354a3feb.png">
IntelliJ version: 2022.2

graphiz failing code: 
`digraph D {

    A [shape=diamond]
    B [shape=box]
    C [shape=circle]

    A -> B [style=dashed, color=grey]
    A -> C [color="black:invis:black"]
    A -> D [penwidth=5, arrowhead=none]
}`

**Comment by ironScripter** [comment]
I am having the same exact issue.
I am using GoLand Version 2022.2.4
Plugin Version 1.4.1

**Comment by alexbepple** [comment]
Is this on Apple silicon? Then the issue is probably a duplicate of #26.
If this is not on Apple silicon, it might be helpful to provide additional info.

**Comment by ozyavin** [comment]
thanks @alexbepple yea, it is probably it since i am running on Apple silicon

**Comment by ozyavin** [comment]
closing as duplicate of #26
