### ISSUE TITLE
Use newer version of graphviz java library

### ISSUE THREAD

**Issue by fsparv** [bzixilu/dotplugin#35]
The current version appears to be 0.12.1 and was downgraded for some mysterious reason from 0.14.2 with no explanation as to why in the commit message. Current versions of the guru.nidi.graphviz (0.18.1) fix a number of bugs including https://github.com/nidi3/graphviz-java/issues/85 which is biting me right now.

**Comment by bzixilu** [comment]
Fixed in 1.5.1
