### ISSUE TITLE
GUI / Display Graph

### ISSUE THREAD

**Issue by cbitterfield** [bzixilu/dotplugin#9]
Does this plugin have a preview or ability to show the graph? I have not found the correct menu if it does.

**Comment by bzixilu** [comment]
@cbitterfield graph preview is not supported yet, but I'll try to add this functionality ASAP.

Thank you for the feature request!

**Comment by bzixilu** [comment]
![Screenshot from 2020-01-21 13-50-02](https://user-images.githubusercontent.com/1190092/72806346-4d994b00-3c55-11ea-9466-6f9bb33705a3.png)
Basic graph preview has been added, will be published soon

**Comment by SpyroTEQ** [comment]
Hello,
I was wondering the same ("does this plugin have a preview?") but I don't have the 3 buttons on the top right... I'm on latest version apparently (May 2020), the `dot` file seems syntaxically recognized, but I don't know where to get the preview. Is there something I missed?

![Capture d’écran de 2020-05-17 19-17-48](https://user-images.githubusercontent.com/2360702/82155171-3e2cb600-9873-11ea-9d6a-9072c86fb6ba.png)

Thanks!

**Comment by bzixilu** [comment]
@SpyroTEQ graph preview was added in 1.2 version of dotplugin, but for some reason, version of your plugin is still 1.1, probably because of 2019.3+ compatibility with IDE. 
Could you please check what version of IDE are you currently using?

**Comment by SpyroTEQ** [comment]
Oh, I didn't think of that: I'm indeed on Intellij Ultimate 2019.2
So it means the plugin v1.2 is only 2019.3+ compatible, hence I'm on "last version" of the plugin for the "old" IDE branch I'm using, right?
I'm gonna update the IDE and check this out. Thanks for the help! :)
